algorithm: supervised 
save_dir: ./saved_models/places
save_name: d3_mlp05_places_test
resume: True
load_path: ./saved_models/places/softmax_places/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 10
num_train_iter: 10240
num_eval_iter: 128 #256
num_log_iter: 4 #256
batch_size: 256
eval_batch_size: 256
ema_m: 0 #0.999
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
net: openai_clip_vit_large_patch14
net_from_name: False
data_dir: /mnt/sda/public/Places365_256/places365_standard/
dataset: places
train_sampler: RandomSampler
num_classes: 365
num_workers: 12
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10187
dist_backend: nccl
gpu: 0
freeze_backbone: False
extra_fc: None
sample_type: None
loss_type: softmax
decoder_depth: 3
decoder_mlp_ratio: 0.5
decoder_num_heads: 4
